### ISSUE TITLE
_compute_centroid_quantile can cause a runtime error in cython_trees

### ISSUE THREAD

**Issue by pgr** [CamDavidsonPilon/tdigest#5]
When trying to batch update a tdigest object with a set of specific data, it results in a run time error due to a stack overflow in NodeStack.push().  

A small example of this can be see at https://gist.github.com/pgr/9b2c4e745a45142eb88b

---

tdigest version: a70e3bde10374cd2d6d32b762e28ae283c98f0a1
bintrees is v2.0.2
sys.version is ['2.7.8 |Anaconda 2.2.0 (32-bit)| (default, Jul  2 2014, 15:13:35) [MSC v.1500 32 bit (Intel)]']

**Comment by CamDavidsonPilon** [comment]
Thanks for the detailed issue @pgr. 

Interestingly, I just made an issue today that will resolve this: #4. The problem is the data is in sorted order. 

```
import random
random.shuffle(problem_data)

td = tdigest.TDigest()
td.batch_update(problem_data)
```

works fine. I'll add this as an additional constraint/problem to be addressed in #4.

**Comment by CamDavidsonPilon** [comment]
Oh wait, I was wrong the data is *not* sorted. Strange then that the `shuffle` solves the issue...

**Comment by CamDavidsonPilon** [comment]
I can narrow it down to just this data: https://gist.github.com/CamDavidsonPilon/2357b9d1b2d1401640fc

**Comment by CamDavidsonPilon** [comment]
K got it. It was because I was using an unbalanced binary tree in bintrees: https://github.com/CamDavidsonPilon/tdigest/blob/master/tdigest/tdigest.py#L4

If ordered data was passed in, as it was in both our examples (a subset in yours), then tree becomes very lopsided. When we try to call `iter_items` on the tree, we hit the upper limit of 64 depth (hardcoded in bintrees as `MAXSTACK`). You can see the calls here: https://searchcode.com/codesearch/view/55567668/

Solution is the change to `FastRBTree` in bintrees. I tested this and it works on our data. Only downside is is that it will be slightly slower. I feel this is a fair tradeoff.

**Comment by CamDavidsonPilon** [comment]
Fixed in latest commit!

**Comment by pgr** [comment]
Confirmed, cheers!.
